title: Python | Bumbii Academy
author: Phuc Tran
description: >
  Học lập trình Python cùng Bumbii Academy
theme: hacker
# Optional: enable posts, social links, etc.
show_excerpts: true
header_pages:
  - about.md